import pandas as pd
df = pd.read_excel('Customer Personality AnalysisPaksave.xlsx')
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print("Columns:", df.columns.tolist())
print(df.info())
print(df.describe())
print(df.head())
print("Missing values:\n", df.isnull().sum())
df = df.dropna()
df = df.drop_duplicates()
df['dt_customer'] = pd.to_datetime(df['dt_customer'], dayfirst=True)
df['income'] = df['income'].astype(float)
df['kidhome'] = df['kidhome'].astype(int)
df['teenhome'] = df['teenhome'].astype(int)
df.to_csv('cleaned_marketing_campaign.csv', index=False)
print("✅ Data cleaned and saved to 'cleaned_marketing_campaign.csv'")
